apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.edge.http.conf.template: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /data/nginx-cache;

        location / {
            autoindex on;
        }
    }
  index.html: |
    <html>
    <head>
        <title>Nginx Cache</title>
        <meta charset="utf-8">
        <style>
            .code {
                background-color: rgb(217, 222, 227);
                padding: 2px;
                overflow: auto;
                font-size: 85%;
                line-height: 1.45;
                border-radius: 6px;
                word-break: normal;
                word-wrap: normal;
                box-sizing: border-box;
                white-space: pre;
            }
        </style>
    </head>
    <body>
        <div>
            <h1>Nginx</h1>
            <p>Congratulations! Nginx Ready!<a href="https://github.com/ossrs/srs">SRS</a> works!</p>
            <hr/>
            <h2>Nginx Cache</h2>
        </div>
    </body>
