{{- if (.Values.persistence.enabled) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oryx-pv-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistence.className }}
  capacity:
    storage: {{ .Values.persistence.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistence.path }}
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oryx-pv-claim
spec:
  storageClassName: {{ .Values.persistence.className }}
  volumeName: oryx-pv-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
{{- end }}
